### ISSUE TITLE
"cauchy_em_two_EM":No such file or directory

### ISSUE THREAD

**Issue by zhouxu-github** [BIT-TYJ/EO--RCL#1]
./scripts/run_robust_pcl_reconstruction_example_cauchy_two_EM.sh: line 5: ./scripts/../build/test/ceres/cauchy_em_two_EM: No such file or directory
When I ran it according to the prompts, I found that the executable file could not be found.

**Comment by BIT-TYJ** [comment]
Hello, you can check if the executable file is successfully generated in the corresponding  content, maybe the building process is failed.

**Comment by zhouxu-github** [comment]
Thank you for your answer. In the in-depth search process, I found that the cmakelist file in the test folder did not work properly because ceres was installed incorrectly. Thank you again for making this project open source

**Comment by BIT-TYJ** [comment]
Feel free to communicate and learn from each other.
