### ISSUE TITLE
How to get relevant data in KITTI dataset？

### ISSUE THREAD

**Issue by zhouxu-github** [BIT-TYJ/EO--RCL#2]
Your work is excellent, so I wanted to try to reproduce the relevant parts of your article about the KITTI dataset. However, during the process of preparing the implementation, I found that I did not know how to obtain the relevant input data similar to that in data/cauchy.

**Comment by BIT-TYJ** [comment]
In fact, the work is based on submaps. However, for the convenience of generating input data, I believe that single-frame-based data is also applicable. For odometry data, 3D point pairs between adjacent frames can be obtained through ICP or feature matching methods. For loop closure data (whether correct or incorrect loop closures), 3D point pairs can be obtained through feature matching methods. Organizing them according to the data format provided in the example will suffice.

**Comment by zhouxu-github** [comment]
Thank you very much for your timely reply. If I want to perform corresponding data processing on the KITTI dataset, are there any recommended open source tools or codes that can process the odometer and loop data?

**Comment by BIT-TYJ** [comment]
Odometry can utilize the classic ICP algorithm, while loop closure can employ the traditional FPFH feature descriptor method. Both of these methods should have Python libraries available.
Good Luck!

**Comment by zhouxu-github** [comment]
Thank you very much for your patience in answering my questions. I have benefited a lot from your answers.

**Comment by BIT-TYJ** [comment]
My wechat is tyjtyj188, welcome to communicate.
